import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { adminGetAllCodes, adminDisableCode } from '../../utils/api.js';
import { AlertError, AlertSuccess } from '../../components/Alert.jsx';
import { formatSydney } from '../../utils/formatters.js';

const STATUS_BADGE = {
  active:   'bg-green-100 text-green-800',
  used:     'bg-blue-100 text-blue-800',
  expired:  'bg-gray-100 text-gray-500',
  disabled: 'bg-red-100 text-red-700',
};

export default function BookingCodes() {
  const [codes, setCodes]     = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState('');
  const [success, setSuccess] = useState('');
  const [filter, setFilter]   = useState('all');

  useEffect(() => { load(); }, []);

  async function load() {
    setLoading(true);
    try {
      const res = await adminGetAllCodes();
      setCodes(res.data);
    } catch (e) {
      setError('Failed to load codes');
    } finally {
      setLoading(false);
    }
  }

  async function handleDisable(code) {
    if (!window.confirm(`Disable code ${code.code} for ${code.employee_name}?\nThey will no longer be able to use this code.`)) return;
    try {
      await adminDisableCode(code.id);
      setSuccess(`Code ${code.code} disabled.`);
      load();
    } catch (e) {
      setError(e.message || 'Failed to disable code');
    }
  }

  const filtered = filter === 'all' ? codes : codes.filter(c => c.status === filter);
  const counts   = codes.reduce((acc, c) => { acc[c.status] = (acc[c.status] || 0) + 1; return acc; }, {});

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Booking Codes</h1>
          <p className="text-sm text-gray-500 mt-1">All employee booking codes — view status, disable active codes</p>
        </div>
        <Link to="/admin/employees" className="btn-primary text-sm">Manage Employees</Link>
      </div>

      {error   && <div className="mb-4"><AlertError>{error}</AlertError></div>}
      {success && <div className="mb-4"><AlertSuccess>{success}</AlertSuccess></div>}

      {/* Summary counts */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6">
        {[
          { label: 'Active',   key: 'active',   colour: 'green' },
          { label: 'Used',     key: 'used',     colour: 'blue'  },
          { label: 'Expired',  key: 'expired',  colour: 'gray'  },
          { label: 'Disabled', key: 'disabled', colour: 'red'   },
        ].map(({ label, key, colour }) => (
          <button
            key={key}
            onClick={() => setFilter(filter === key ? 'all' : key)}
            className={`card p-4 text-left transition-colors ${filter === key ? 'ring-2 ring-brand-500' : 'hover:bg-gray-50'}`}
          >
            <p className="text-2xl font-bold text-gray-900">{counts[key] || 0}</p>
            <p className={`text-sm font-medium text-${colour}-700 mt-0.5`}>{label}</p>
          </button>
        ))}
      </div>

      {loading ? (
        <div className="text-center py-12 text-gray-400">Loading…</div>
      ) : filtered.length === 0 ? (
        <div className="text-center py-12 text-gray-400">
          No {filter === 'all' ? '' : filter} codes found.
          {filter !== 'all' && <button onClick={() => setFilter('all')} className="ml-2 text-brand-600 underline">Show all</button>}
        </div>
      ) : (
        <div className="card overflow-hidden">
          <table className="min-w-full divide-y divide-gray-200 text-sm">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-4 py-3 text-left font-medium text-gray-500">Code</th>
                <th className="px-4 py-3 text-left font-medium text-gray-500">Employee</th>
                <th className="px-4 py-3 text-left font-medium text-gray-500">Generated By</th>
                <th className="px-4 py-3 text-left font-medium text-gray-500">Generated At</th>
                <th className="px-4 py-3 text-left font-medium text-gray-500">Expires</th>
                <th className="px-4 py-3 text-left font-medium text-gray-500">Status</th>
                <th className="px-4 py-3 text-right font-medium text-gray-500">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 bg-white">
              {filtered.map(c => (
                <tr key={c.id} className="hover:bg-gray-50">
                  <td className="px-4 py-3 font-mono font-bold text-gray-900 tracking-wider">{c.code}</td>
                  <td className="px-4 py-3">
                    <p className="font-medium text-gray-900">{c.employee_name}</p>
                    <p className="text-xs text-gray-500">{c.employee_emp_id}</p>
                  </td>
                  <td className="px-4 py-3 text-gray-600">{c.generated_by}</td>
                  <td className="px-4 py-3 text-gray-600 text-xs">{formatSydney(c.created_at)}</td>
                  <td className="px-4 py-3 text-gray-600 text-xs">{formatSydney(c.expires_at)}</td>
                  <td className="px-4 py-3">
                    <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${STATUS_BADGE[c.status] || 'bg-gray-100'}`}>
                      {c.status}
                    </span>
                    {c.status === 'used' && c.used_reservation_id && (
                      <Link to={`/admin/reservations/${c.used_reservation_id}`} className="block text-xs text-brand-600 hover:underline mt-0.5">
                        Booking #{c.used_reservation_id}
                      </Link>
                    )}
                  </td>
                  <td className="px-4 py-3 text-right">
                    {c.status === 'active' && (
                      <button
                        onClick={() => handleDisable(c)}
                        className="text-xs text-red-600 border border-red-200 px-3 py-1.5 rounded hover:bg-red-50"
                      >
                        Disable
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
