import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { adminGetRefundRequests, adminApproveRefund, adminRejectRefund } from '../../utils/api.js';
import { AlertError, AlertSuccess } from '../../components/Alert.jsx';
import { formatSydney } from '../../utils/formatters.js';

const STATUS_BADGE = {
  pending:  'bg-yellow-100 text-yellow-800',
  approved: 'bg-green-100 text-green-800',
  rejected: 'bg-red-100 text-red-700',
};

export default function RefundRequests() {
  const [requests, setRequests] = useState([]);
  const [loading, setLoading]   = useState(true);
  const [error, setError]       = useState('');
  const [success, setSuccess]   = useState('');
  const [filter, setFilter]     = useState('all');

  const [actionId, setActionId]   = useState(null);  // id of row being actioned
  const [notes, setNotes]         = useState('');
  const [actionType, setActionType] = useState(null); // 'approve' | 'reject'
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => { load(); }, []);

  async function load() {
    setLoading(true);
    try {
      const res = await adminGetRefundRequests();
      setRequests(res.data);
    } catch {
      setError('Failed to load refund requests');
    } finally {
      setLoading(false);
    }
  }

  function openAction(id, type) {
    setActionId(id);
    setActionType(type);
    setNotes('');
    setError('');
  }

  function closeAction() {
    setActionId(null);
    setActionType(null);
    setNotes('');
  }

  async function handleSubmitAction() {
    setSubmitting(true);
    setError('');
    try {
      if (actionType === 'approve') {
        await adminApproveRefund(actionId, { notes });
        setSuccess('Refund approved and processed via Stripe. Customer has been emailed.');
      } else {
        await adminRejectRefund(actionId, { notes });
        setSuccess('Refund request rejected.');
      }
      closeAction();
      load();
    } catch (e) {
      setError(e.message || `Failed to ${actionType} refund`);
    } finally {
      setSubmitting(false);
    }
  }

  const filtered = filter === 'all' ? requests : requests.filter(r => r.status === filter);
  const counts   = requests.reduce((acc, r) => { acc[r.status] = (acc[r.status] || 0) + 1; return acc; }, {});
  const pendingCount = counts.pending || 0;

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Refund Requests</h1>
          <p className="text-sm text-gray-500 mt-1">
            Review and approve refunds generated by customer cancellations
          </p>
        </div>
        {pendingCount > 0 && (
          <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-semibold bg-yellow-100 text-yellow-800">
            {pendingCount} pending review
          </span>
        )}
      </div>

      {error   && <div className="mb-4"><AlertError>{error}</AlertError></div>}
      {success && <div className="mb-4 cursor-pointer" onClick={() => setSuccess('')}><AlertSuccess>{success}</AlertSuccess></div>}

      {/* Inline action panel */}
      {actionId && (
        <div className="card p-5 mb-6 border-2 border-brand-200 bg-brand-50">
          {(() => {
            const req = requests.find(r => r.id === actionId);
            if (!req) return null;
            return (
              <>
                <h3 className="font-semibold text-gray-900 mb-2">
                  {actionType === 'approve' ? 'Approve Refund' : 'Reject Refund'} — {req.customer_name}
                </h3>
                <p className="text-sm text-gray-600 mb-1">
                  Refund amount: <strong className="text-gray-900">AUD ${(req.refund_cents / 100).toFixed(2)}</strong> ({req.refund_pct}% of {parseFloat(req.price_aud || req.price_cents / 100).toFixed(2)})
                </p>
                {actionType === 'approve' && (
                  <p className="text-sm text-amber-700 bg-amber-50 border border-amber-200 rounded p-2 mb-3">
                    This will immediately charge Stripe and send the customer a confirmation email.
                  </p>
                )}
                <label className="label mt-2">
                  Notes <span className="font-normal text-gray-400">(optional — internal record only)</span>
                </label>
                <textarea
                  value={notes}
                  onChange={e => setNotes(e.target.value)}
                  rows={2}
                  className="input resize-none mb-4"
                  placeholder="Any notes for the record…"
                />
                <div className="flex gap-3">
                  <button onClick={closeAction} disabled={submitting} className="btn-secondary">
                    Cancel
                  </button>
                  <button
                    onClick={handleSubmitAction}
                    disabled={submitting}
                    className={actionType === 'approve' ? 'btn-primary' : 'btn-danger'}
                  >
                    {submitting
                      ? (actionType === 'approve' ? 'Processing…' : 'Rejecting…')
                      : (actionType === 'approve' ? 'Confirm Approve' : 'Confirm Reject')}
                  </button>
                </div>
              </>
            );
          })()}
        </div>
      )}

      {/* Summary counts */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        {[
          { label: 'Pending',  key: 'pending',  colour: 'yellow' },
          { label: 'Approved', key: 'approved', colour: 'green'  },
          { label: 'Rejected', key: 'rejected', colour: 'red'    },
        ].map(({ label, key, colour }) => (
          <button
            key={key}
            onClick={() => setFilter(filter === key ? 'all' : key)}
            className={`card p-4 text-left transition-colors ${filter === key ? 'ring-2 ring-brand-500' : 'hover:bg-gray-50'}`}
          >
            <p className="text-2xl font-bold text-gray-900">{counts[key] || 0}</p>
            <p className={`text-sm font-medium text-${colour}-700 mt-0.5`}>{label}</p>
          </button>
        ))}
      </div>

      {loading ? (
        <div className="text-center py-12 text-gray-400">Loading…</div>
      ) : filtered.length === 0 ? (
        <div className="text-center py-12 text-gray-400">
          No {filter === 'all' ? '' : filter} refund requests.
          {filter !== 'all' && (
            <button onClick={() => setFilter('all')} className="ml-2 text-brand-600 underline">Show all</button>
          )}
        </div>
      ) : (
        <div className="card overflow-hidden">
          <table className="min-w-full divide-y divide-gray-200 text-sm">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-4 py-3 text-left font-medium text-gray-500">Customer</th>
                <th className="px-4 py-3 text-left font-medium text-gray-500">Vehicle</th>
                <th className="px-4 py-3 text-left font-medium text-gray-500">Pick-up</th>
                <th className="px-4 py-3 text-left font-medium text-gray-500">Refund</th>
                <th className="px-4 py-3 text-left font-medium text-gray-500">Requested</th>
                <th className="px-4 py-3 text-left font-medium text-gray-500">Status</th>
                <th className="px-4 py-3 text-right font-medium text-gray-500">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 bg-white">
              {filtered.map(r => (
                <tr key={r.id} className="hover:bg-gray-50">
                  <td className="px-4 py-3">
                    <p className="font-medium text-gray-900">{r.customer_name}</p>
                    <p className="text-xs text-gray-500">{r.customer_email}</p>
                    <Link
                      to={`/admin/reservations/${r.reservation_id}`}
                      className="text-xs text-brand-600 hover:underline"
                    >
                      Booking #{r.reservation_id}
                    </Link>
                  </td>
                  <td className="px-4 py-3 text-gray-700">{r.vehicle_name}</td>
                  <td className="px-4 py-3 text-xs text-gray-500">{formatSydney(r.start_utc)}</td>
                  <td className="px-4 py-3">
                    <p className="font-semibold text-gray-900">
                      AUD ${(r.refund_cents / 100).toFixed(2)}
                    </p>
                    <p className="text-xs text-gray-500">{r.refund_pct}% of total</p>
                  </td>
                  <td className="px-4 py-3 text-xs text-gray-500">{formatSydney(r.requested_at)}</td>
                  <td className="px-4 py-3">
                    <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${STATUS_BADGE[r.status] || 'bg-gray-100'}`}>
                      {r.status}
                    </span>
                    {r.status !== 'pending' && r.reviewed_by && (
                      <p className="text-xs text-gray-400 mt-0.5">by {r.reviewed_by}</p>
                    )}
                    {r.notes && (
                      <p className="text-xs text-gray-400 mt-0.5 italic truncate max-w-[120px]" title={r.notes}>
                        {r.notes}
                      </p>
                    )}
                  </td>
                  <td className="px-4 py-3 text-right">
                    {r.status === 'pending' && (
                      <div className="flex justify-end gap-2">
                        <button
                          onClick={() => openAction(r.id, 'approve')}
                          className="text-xs text-green-700 border border-green-300 px-3 py-1.5 rounded hover:bg-green-50"
                        >
                          Approve
                        </button>
                        <button
                          onClick={() => openAction(r.id, 'reject')}
                          className="text-xs text-red-600 border border-red-200 px-3 py-1.5 rounded hover:bg-red-50"
                        >
                          Reject
                        </button>
                      </div>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
